apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cert-manager-issuer
  namespace: cert-manager
spec:
  gatewayClassName: traefik
  listeners:
  - name: http
    protocol: HTTP
    port: 8000
    allowedRoutes:
      namespaces:
        from: All
