---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterissuer.yaml
- gateway-issuer.yaml
- https://github.com/hetznercloud/csi-driver//deploy/kubernetes/?ref=v2.17.0

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: infra-ksops
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - ./secret-hcloud.enc.yaml
