---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    allow:
      - dependency-type: 'all'
    groups:
      npm-deps:
        patterns:
          - '*'
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: monthly
    allow:
      - dependency-type: 'all'
    groups:
      bundler-deps:
        patterns:
          - '*'
