# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tech Werkers NL
email: contact@techwerkers.nl
description: Tech Workers Coalition Netherlands is where tech workers come together to build collective power in our workplaces.
url: 'https://techwerkers.nl'
baseurl: ''
timezone: 'Europe/Amsterdam'

# Build settings
feed:
  disable_in_development: true
  collections:
    - events
    - resources
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-seo-tag
  - jekyll-sitemap

## SEO, Open Graph etc..
twitter:
  username: techworkers
  card: summary
facebook:
  publisher: 105285494190738

social:
  name: Tech Workers Coalition Netherlands
  links:
    - https://techwerkers.nl/

sass:
  style: compressed

include:
  - _pages
  - _redirects
exclude:
  - .jekyll-cache/
languages: ['en', 'nl']
exclude_from_localizations: ['assets', 'admin', 'vendor', '_redirects']
# We don't want english to be any more or less special than other languages
default_locale_in_subfolder: true

# header menu items
# text: the i18n key for link
# namespace: the namespace that matches the page's frontmatter namespac
header_themes:
  - text: about
    namespace: about
  - text: events
    namespace: events
# TODO: Uncomment when we want to go live with resources
#  - text: resources
#    namespace: resources

permalink: pretty
future: true
collections:
  events:
    output: true
    permalink: events/:title
  resources:
    output: true
    permalink: /resources/:title
    # Note: this does nothing but is here for documenting the default
    permalink_nl: /bronnen/:title
  pages:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ''
    values:
      image: /assets/img/beat_the_boss.jpg
  - scope:
      type: 'events'
      path: ''
    values:
      layout: 'event'
  - scope:
      type: 'resources'
      path: ''
    values:
      layout: 'resource'
