services:
  jekyll:
    image: jekyll/jekyll:4 # Same version as in the Gemfile
    command: jekyll serve --watch --incremental --livereload
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle # Cache gems
