[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.2"

# Set base URL for deploying previews
[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# Set base URL for deploying branches
[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://techwerkers.netlify.com/*"
  to = "https://techwerkers.nl/:splat"
  status = 301
  force = true

# Root domain redirect based on Accept header
# Netlify only redirects on first lang. NL is the default otherwise.
[[redirects]]
  from = "/"
  to = "/en/"
  status = 301
  force = true
  conditions = {Language = "en"}

[[redirects]]
  from = "/"
  to = "/nl/"
  status = 301
  force = true

# Root Redirects for localised content types.
# Netlify splat operator cannot be used on root due to it redirecting FE assets
# Adding new content types:
#  - There should be a pair of "en" and "default" (nl) for each content type
[[redirects]]
  from = "/events"
  to = "/en/events"
  status = 301
  force = true
  conditions = {Language = "en"}

[[redirects]]
  from = "/events"
  to = "/nl/events"
  status = 301
  force = true

[[redirects]]
  from = "/join"
  to = "/en/join"
  status = 301
  force = true
  conditions = {Language = "en"}

[[redirects]]
  from = "/join"
  to = "/nl/join"
  status = 301
  force = true

[[redirects]]
  from = "/resources"
  to = "/en/resources"
  status = 301
  force = true
  conditions = {Language = "en"}

[[redirects]]
  from = "/resources"
  to = "/nl/resources"
  status = 301
  force = true

[[redirects]]
  from = "/posts"
  to = "/en/posts"
  status = 301
  force = true
  conditions = {Language = "en"}

[[redirects]]
  from = "/posts"
  to = "/nl/posts"
  status = 301
  force = true

# Localised 404 redirects
# Netlify shadowing means that pages that do exist behind the * will render if they exist
#   otherwise they will return the referenced 404.
[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/nl/404.html"
  status = 404
