[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.142.0"

# Set base URL for deploying previews
[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

# Set base URL for deploying branches
[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
