apiVersion: v1
kind: Secret
metadata:
    name: dex-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:i9met/SCd8QskPUWQ5Hf7OKdSLfePv+szYwjQcZibNfI4ll7QHgi+QFIpzA2/+VGg9AACVvum8DJilAZLaJZJipmrazPuyOj9wQ4YpYJW3fOBLVDPSxW5HIC8SuEmD4a75vm28ZSuE/QQf2T5kikHL5urZUVjLCpaiFRu6cIk+K7bV3JP0U0fidoFw4VdDPcapz9W0m57NE//onugcqNve0E6RrD45eyNX/gaZy2boQ43XdzJTozcclDi4rJfk7QNguewMRH3wbarT93LWqFHKjqVPG3O+UBjARZqjCh/e0tZb3sa6aH7Fy348voEskmIrXRq6nkjpA0h1BylVJk5a6HzFv5WQg94lAqDWRVMA2C3ryPBkYhMs25R2hGXF1yxc64GdQANjYQCnZ2t3c//ApMTyq4nRKpeI9y9MKKNBmGqSpjEGFK6SQuKkrRCnzuVDU/VLAgjrVXdFeQCLlkgnDMJMVGau7LpbmhZqiNS04I9LKOGKUDWumd4oljRQHsKerrDLZ/8VSK8u8eA5CTWHXaRxcm2K/gvYgPUWLhsPpU8uiaIHqSLs7CPK/zuu4a3n8ytlU+arNsVL+EgPDItQ7lqr24Tnp0yrrGY65ht+sXfon+Jiamhh7gegYp2e21OXBLxQMBcVgDAaBcODNz4qaF8cNG5Nm/KwuvLPmPBBs5k0PKaUAHsoO4zV0gAZv5yqxqq1+TCwVR1nKUVUFgg9go1eM5U5n6fe+vNn62o23Fs5ujj0OhURmcImgCz2nxKA==,iv:pvP3IafG3JJ5EEnPAfZBGrBSCFCkjPke6Fe268enHe8=,tag:+Ta3yDWN4/vsPzkFeD76uw==,type:str]
sops:
    age:
        - recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aEZCdTJRVDgvN1A2RytJ
            QStrTGR0NldodllUdXVnc1V1Qk1aQ0QwZnp3CkROMDhpZVpVaTl1SmM4Vi9mVmdi
            ZWF0VzBRSkxPN0FYMTJWYlFYQXpYZUUKLS0tIEJNa1JmSFM4UHcyUWlyR1pCSkRi
            QTlwd3NyYUZHK25qbnkyVGxod1BUNmcKnSr8qKRN80GsHE6yKE38PdB40DZRfs+9
            V7WhWQchllh4D9QOzR+lxsEk12J7atuGpU8li3Jb7OjnjaiuQkr5mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T09:24:45Z"
    mac: ENC[AES256_GCM,data:XZaWPt6G5cqblbshdxXxHmeSzT5uP6N6xXIwmmjoXbjHy8DdWzSEQy/4YCDXZwE1kiqee50ldstFH+KUKyn6pNqwhIAcQPh6GwWzVIH7psMo4fsyseKgjCmm0HSkPln1e6eDMFPx90sueLEX8cK0/YTMCuDLGhwQag/xJyxUuW8=,iv:z1UaCthJtsd7xnbfzY/3pSxA0Qkt2qq6TaDJH02a6Ps=,tag:3mdsiokV6hJ6fKJi0sBO1w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
