apiVersion: v1
kind: Secret
metadata:
    name: dex-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:pPbWqiklnJTn+0dzV180bPgFZQmyDHPcP3rjyEgtsv0rnQaWgrQADEqoUcwsuFQXl/yZvfQcuRAOTAE4bnYFQGmenmIGhYdKMXYyJ1ZSAduIBjFrfhDfX8t+xjf4HCqUc/6Sr+oUHVGVFZBGH2SoxivNv1VyhmR4dlnEvOS4FwNNtQsUWg0+TT8PFk0uy+3LMWKpTC2VsZZRUbZ2lSuDCgjWQRVy3DAuqulKoYaB86TWnZ2eVGziy6xM6okv8D8PmMrOYVvK2LTYADg2psoqg6ADjxS9fgvfb5/JAQWzEJTdX7/M7sH5fFAojYa52OfstlXQolWvSGyA4pafYzGh6/wDx/eD8Kx6bZug1qlCf2XOFktCGYK2QZsiE5swEXQ9JqnC9ukA5Mn1Fpf3u6zWi0tsoRhtf6qzxtSPZICOhsdegWJeYJHMtN1ACkavydAowSK30BegEjtiQqnXEaKqbedUQ3ZFH1Ed4B7PlAuDTQbXP7EjfQD95uPLip26jrIzXEFWQOY6KYuK3qca6dkY5XgYbx1Fnd9SrEzLJzOjQkNNXwxd+TEsNYgWl2XCzF+aeaoinAGzA8JxK73ihUt6Nepu+82fFozi8wFSov7EaZPGC3dcegKk4YGTsrdsvLKqFS+Ajfl3HjkE6r1KZNX5zNkfy8wRr0qA5rZMIKo8tvBlOXKKKucU1N6YT7Mmkm0avJsvmxJic95+c4/CbLBUoUoJ3Oavhoq3EPEDZFdvVPCRuYC7t7lzc9T9VyYv9DpsI7R+rLhkM/gcZPSU2AS8CtUxHbOGJEA10zIfyEEhCZlxANEMzbZ6mvLCj9vLNvN9qda+U5JjnnkJAjb5Eo1/xYCp2TsjRsQWdrn63gEr57Z94jVXUVgQyXrAqGZ6mceqo7TzRlZ7TIlD2jHQOHoAh36WzCw1zqZJt0uz+WZVcqeAh5S7N8gkz8PAi45yqw3dDEMX0g76ifS9x5FqeFXSjaU=,iv:V26C6MRgzQN/FPFpK4OpSb4Pt480xhEsmh+Un8w1nJA=,tag:6nEGOyhH8xd3xBCmln/HWQ==,type:str]
sops:
    age:
        - recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aEZCdTJRVDgvN1A2RytJ
            QStrTGR0NldodllUdXVnc1V1Qk1aQ0QwZnp3CkROMDhpZVpVaTl1SmM4Vi9mVmdi
            ZWF0VzBRSkxPN0FYMTJWYlFYQXpYZUUKLS0tIEJNa1JmSFM4UHcyUWlyR1pCSkRi
            QTlwd3NyYUZHK25qbnkyVGxod1BUNmcKnSr8qKRN80GsHE6yKE38PdB40DZRfs+9
            V7WhWQchllh4D9QOzR+lxsEk12J7atuGpU8li3Jb7OjnjaiuQkr5mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T10:36:01Z"
    mac: ENC[AES256_GCM,data:fEzpk/ixNkwht0s60OcZXYAqPxDBdrVIS3eJIMe6giddu1aAhHfy/oz4SqNIlFE1AXYq8fAiVpt7wjLHFLY4pJMq3kFVxmZcfe+tFT1omfY7kPjP7ra0iyFcTqelIoj7A5or5ry0O/6J39McKWKvedY1ESZCj6l8wVLWivDCnss=,iv:bocwRw7oMPzZA8aHqnPbP/kjaZyhXpdKaYX/++w+gs4=,tag:8l8UcGBMP7fMZRyLmFGesg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
