apiVersion: v1
kind: Secret
metadata:
    name: dex-env
    namespace: dex
type: Opaque
stringData:
    CLIENT_TRAEFIK_SECRET: ENC[AES256_GCM,data:fHJ+kOhnqz1mSWqtomY2ROk+aeqBqk1icj/KWmEh2bzi9hEuEvf5sSirxOOW9/9VKrDRPeQRrumbRD8zsA+D8w==,iv:zhOmpOBj9HaFy4pwPHmsD4x+qmtVVwUVwUIXouPw38c=,tag:TVzed83V8dP2JS5eSdkMgQ==,type:str]
    DEX_STATIC_CLIENT_TRAEFIK_SECRET: ENC[AES256_GCM,data:vHNTj6l+qhKiUbbb1EOeH6pXG0HGGh0WphqujpIy0JX2RUvnkQhu5AT78EeN77t/Eaen0HayVNoxmjuGhmXbYA==,iv:crTBFyRv/UEUkqR1p3V6eJEOyr/bDrE6Lih2RUJa1kw=,tag:qtrZLh38mHVMsih9ifwqeA==,type:str]
sops:
    age:
        - recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6K3ZEUk10WGFjcTZXRU82
            UTMzUGlaRlRYbk5OMmFyTTl2Ui9sOTdFMzJBCmEwbjZhTzZCa0RmV2xjdmxxR1F2
            Zk9HUExwMHZQMjY3VFIyUFVkUTBEblUKLS0tIGRKR2Q3UDQyWmlxTU1FLzJvT2Jn
            TVNqY2JrTFJ0VFhzVW9sTXRQczB4d2cKqCgzdY7aumjtbufHhVrig2cGe/Lt+z3W
            KSWzMGvRNFbdRIF+IRjmGceT1IvbMlM6MIPwes/MRgqGDv9hzO3BBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T09:27:57Z"
    mac: ENC[AES256_GCM,data:JX4eRcEndIR+A+vnIcj/IdY4OzxBPaI4ciFYSM3RO3Kb6CtfZ11UTH8QWHk53CrmzAAlPv5RtYrXXaCbkLPSg0LbIJEinj0n3S9wE/d+njH5H31IEZHJxRMqAUnfiTqhqwMDGw3LJhnMK/LkdfYwUMkrYVozaql/huNERy23mSU=,iv:TRyIayIoVEFlyx5afLANyKZst1CKBrUfTcgM+yjgq+Y=,tag:+kXm9yAdUynY/tcZgtBCLQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
