apiVersion: v1
kind: Secret
metadata:
    name: dex-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:rn3+eiucjGyhLeRo1TqOgD/jGP0JmzdusCJSin7x7BqK/SKGoVeFNDJnTcbZ2csm2tTBRrOfiOOHWa2r5+m7aOdtl25Yjj954QHpB0LkSKNwMcUamkEfL9TBRql3DI9C5qAyJrFBHuuM+90BlubZUu5gEQgIPgDeqO8dVmM3U4/RJUJL6IXfo5TOmZeF1A2Xx6pLsQwZmg/rf8wu0y/772buSO9vDcPgaXDllzCh2o/OoAJLp5QH4zC+sNqsbdtmIP/URwXWf06GDXzAMruNN0Hj+HfqQr/8kABnWWGf27punpy4kbMMQRxNnSF6yEdJdkchiiVeC/VDFgEiBMMEZLgc1uZillH+ShpU2KMJIlIc0lSQGZ9tbbHVO941lVJOcwl/CCAjrnP/D5Rmsx6BjqQgavQbkpRISwm+zVhMgBNQYnWSUebriOyXDrFGbXVzbq3xffCvGMltUAO1H1l2vhecaM+Otf4kMa1rBKYkiWNG0SGrbtROCQfjRmWQBl5EBs87gGJEnQ5IJgX/atnHH2f0ebd1AGSVub8vI0QLe7doak38sH4geitJp4GUytjYNiK8UQIDi+F+PurPOTO+qydAltzt48tX8Rg/0T0G30QFzefWdYoiNwbR4cFzXq979SKQhhgzTBDOHDltxGw00ZQUlOT6aI/+r7LZwNHWGlaSJc4BZXHQg8YdOYUuaVnf9nWBHpLp+6gooHQxYDt5ozwZPqYrNEgZpiGD6kXxb5RtW8O1+PeQ4VfCtj09P22DDlus+KpMVFQl1sIfX+PcJHVv9boCMnKAFzWj+hNFGkpHIuN+PFZBdFAPv5g/6Ee2gurWZvF3Os1Pj28wxNA+oJ7vTb74GatgduQxrw5NyTYDzWDvAvomCwAzno58QVxWCcHEecIS4gw+faSyq+7l7ku2cpEtIrrxnXreWqK23W43RfrgQVnxK+SZNsiggA1E39TYWGrQ0h4XQvFu,iv:ymZB5J/wl053Qu3F9vSSbRjjx9vKCXEcp0TyjtSv4cQ=,tag:Ru6lJPgsWSEPB6stgwu9lQ==,type:str]
sops:
    age:
        - recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aEZCdTJRVDgvN1A2RytJ
            QStrTGR0NldodllUdXVnc1V1Qk1aQ0QwZnp3CkROMDhpZVpVaTl1SmM4Vi9mVmdi
            ZWF0VzBRSkxPN0FYMTJWYlFYQXpYZUUKLS0tIEJNa1JmSFM4UHcyUWlyR1pCSkRi
            QTlwd3NyYUZHK25qbnkyVGxod1BUNmcKnSr8qKRN80GsHE6yKE38PdB40DZRfs+9
            V7WhWQchllh4D9QOzR+lxsEk12J7atuGpU8li3Jb7OjnjaiuQkr5mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T09:56:58Z"
    mac: ENC[AES256_GCM,data:gAEkNwh9bobyiSePnMLygd/g/1RtXdZwIgMgPmEbE9y8UWP2syR9LWA/OzmE0j0/d0ud1TG9Q0QTmX6geppEb85G+NA/luKh6SZR47YwgTH4mUlwU7+j8iSUoFF+QyTijg2ROCfxOblmW6CbqCt1M/GgM8szfpNF7sN+9YGBaFo=,iv:TzXGAyV5i8IRgHdfZ5BlMf56iEz5S6nmT5ytTHzxWsY=,tag:wl09UZMZG0pz8F1E4tGa7A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
