apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-dex
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:RrGn39DXZN2HV0ccEA==,iv:3Bis4AtV4xWI1KQ1Aj6FThNkFnRp6wxOTE4Wk3/4+Pk=,tag:dk9GBIRVeTf2Btb6FxIaaw==,type:str]
    client-secret: ENC[AES256_GCM,data:hIgzE8sDJo71fRVUhbdcQHhpkwFAySCQmBXz8tVsgmB6dyyYJAfloR3xTAfalni63CqlX/ia+TZJ0sXCPNoSng==,iv:209m/rec4MDVp+UUR+lr/aiqoP2rB7S7eVmJYRbiDZM=,tag:aaAhpUsUmer1Xl74P6KftA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:EO1hhjfs+PSNam2zJGtNxq9yuLGSdHFettilWaLPvMc=,iv:SoCn04OMR+5ujgTI3cqypKBr6f9ObnIwLJDu8knFqeA=,tag:/EZmKMdgp7Os8QMGkLYuaw==,type:str]
sops:
    age:
        - recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla2Q5Ly95TlFZQUNXdytu
            cUVGS2czVFNxNXlucWNVOEs1TkxhNE9UeXp3Cmp5ckJCRVFrMkd0ZFo4SlBVRWdF
            UUt6VnI5VGtGZ2RJNkZKSTdnUWlhSTQKLS0tIGFlaHVISVI5OWdKVGxCazVVSjBj
            SG1oUHF3MFdCeXdkSVd0T3MrRTdUcFEKrnG366XrCIR1m9wgmXYx+KodW8ypiRHq
            VdCubpiU6zC11K8/IIFk1zn/2x0k9QEayrb9kJiGsrEftDgYZWpSSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T09:41:11Z"
    mac: ENC[AES256_GCM,data:WFVgNwqfwtEPgggR7lexDGDbENcSYcLro4WSm7vlCpAGu6UK9TKuTpA+FUrECzioiepsU/T+6nwkbrLFDIAaT+C3babJT6yOv4Q+a4q29rArYeyj7/e1IKsmCNr1/bRimxsanYJBl8vrApCQ4B43j5XLKfQfT+XWTN7PIMsc4Yo=,iv:1wpahlI8OVmQZ5XYZvNynHZjgPB4Aey1HSpc6jVau8E=,tag:Gv9kDBqD0fIBuqFh/Pkr+Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
