local_backend: true # run `npx decap-server` to access /admin locally

# enable PRs and status checks for main branch protection
publish_mode: editorial_workflow

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  squash_merges: true # We are not super interested in the draft history

media_folder: 'assets/img'

collections:
  - name: 'event' # Used in routes, e.g., /admin/collections/blog
    label: 'Event' # Used in the UI
    folder: '_events' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD HH:mm',
        }
      - {
          label: 'Locations',
          name: 'locations',
          widget: 'select',
          multiple: true,
          default: ['The Netherlands'],
          min: 1,
          options: ['The Netherlands', 'Global', 'Online'],
        }
      - {
          label: 'hide signup form',
          name: 'hide_form',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Canonical url',
          name: 'canonical_url',
          widget: 'string',
          required: false,
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Optional image for SEO',
          name: 'image',
          widget: 'image',
          required: false,
        }
