apiVersion: v1
kind: ConfigMap
metadata:
  name: excalidash-backend-env
data:
  PORT: "8000"
  DATABASE_URL: "file://app/prisma/excalidash.db"
  NODE_ENV: "production"
  FRONTEND_URL: "https://excalidash.techwerkers.nl/"

