---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: excalidash

images:
- name: zimengxiong/excalidash-frontend
  newTag: 0.3.2
- name: zimengxiong/excalidash-backend
  newTag: 0.3.2


resources:
- ns.yaml
- ../ext/middlewares/
# Gateway, routes, tls
- certificate.yaml
- gateway.yaml
- httproute.yaml
# Excalidash core
- configmap-backend-env.yaml
- configmap-frontend-env.yaml
- service-frontend.yaml
- service-backend.yaml
- deployment-frontend.yaml
- statefulset-backend.yaml

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: excalidash-ksops
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - ./secret.enc.yaml
