apiVersion: v1
kind: Secret
metadata:
    name: excalidash-env
type: Opaque
stringData:
    CSRF_SECRET: ENC[AES256_GCM,data:gIU2vGqWkbt415bKOZByo23qPbSHyUZcJJQSG3eC12eJD6nIMOSSw4Lxojg=,iv:DVlStLoktRPz7lNY1ZZ3VwmgPW0GTvyT0jh5kodeSj0=,tag:n7jUXk+8R2xCdbM/cXUN0A==,type:str]
sops:
    age:
        - recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzam5CMWhrT3g2eWpyVEFW
            VlNrK3VYM0J4RS95THcyVzdHS1lqU3I4QkRvCk03ZjZjQWxYcldXa2JhVVdDMzNi
            UHhaRUJqekxzTy9SYjBTVUpELzFTTVkKLS0tIHdGZFpkeisxZk1DK2xuK2ZnMmE2
            YlR6d2JIeTZxRE5kZGllenh1MnBudXMK5aUj2dSMOTr+t4vHqj3NJBewq+1Ika4N
            w6/Ylq0K1LuQQZILGjt+6zUzW/Jqcks8GXJKy0IXG7T2gCbS74lEYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T10:15:34Z"
    mac: ENC[AES256_GCM,data:g9WMetTcPDgGRvT+8KwJIXWTU3AjpvnY3+zoyQyMseiZeVEOFv1nmacJ9RkucR0Lf2bLvrqE2g2tR+0v3XfqJWxvWFcZsTZU6KbE/4mLhAmbUWa+Mkp2YzBJO4vj6MoUEyymp8OE669v3pVsXJy6UlflWd7YWVr5wcEltv34BBs=,iv:pCZ//Ma5SIUc+lfwFRHpL+TiCUqHgsM7cdQMiHYakDQ=,tag:sz5b33yjqL6bt3YWd47PHA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
