apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: cert-manager-issuer
            namespace: cert-manager
            kind: Gateway
