apiVersion: v1
kind: ConfigMap
metadata:
  name: listmonk-listmonk-env
data:
  LISTMONK_app__address: "0.0.0.0:9000"
  LISTMONK_db__user: listmonk
  # LISTMONK_db__password: "" set in the secret
  LISTMONK_db__database: listmonk
  LISTMONK_db__host: listmonk-postgres.listmonk.svc.cluster.local
  LISTMONK_db__port: "5432"
  LISTMONK_db__ssl_mode: disable
  LISTMONK_db__max_open: "25"
  LISTMONK_db__max_idle: "25"
  LISTMONK_db__max_lifetime: 300s
  TZ: Etc/UTC
  LISTMONK_ADMIN_USER: admin
  # LISTMONK_ADMIN_PASSWORD: "" set in the secret
