---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: listmonk

images:
- name: listmonk/listmonk
  newTag: v6.0.0
- name: postgres
  newTag: 17-alpine 

resources:
- ns.yaml
# Gateway, routes, tls
- certificate.yaml
- gateway.yaml
- httproute.yaml
# Dependencies (Postgres, redis)
- configmap-postgres.yaml
- service-postgres.yaml
- statefulset-postgres.yaml
# Listmonk core
- configmap-listmonk-env.yaml
- service-listmonk.yaml
- statefulset-listmonk.yaml

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: listmonk-ksops
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - ./secret-postgres.enc.yaml
  - ./secret-listmonk.enc.yaml
