apiVersion: v1
kind: Secret
metadata:
    name: listmonk-listmonk
    namespace: listmonk
type: Opaque
stringData:
    LISTMONK_db__password: ENC[AES256_GCM,data:rjxB3pUCa2B6F/Q5KiNzfBhkfrTEzmwUzGrHwrq1FPRQtmBCxNRM1VVg4D1JM1LJslBxFs0ZkM9EH9p8/8ue6U0=,iv:pSrldunrE78RqPYcZKm3NMbjuZhpYNS3OY7Y7U2b3r4=,tag:NPN8GIB8MXZ+iSE/putHaw==,type:str]
    LISTMONK_ADMIN_PASSWORD: ENC[AES256_GCM,data:JeugVcre3yzTWyXeDI/nGQyh/qssa9tTAhnjiJgvEdA=,iv:ip3uzD/W5emyUDbfflPUff7v5q5OHASaKB8aNRgYztY=,tag:dE50XfX7RfQvY7i+z8d1MQ==,type:str]
sops:
    age:
        - recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIc2VDRUs0b1Rjc3I0QXVw
            ME44U3FLVXZIYnBtemZOeHJ2MGc5R1NEajNnCjdQN1hPZzhDZXp4VVFuN1VuWDlm
            Q2s4OENXeE5nbmxvYmI0YmNDTVBkRHcKLS0tIGVSZEdUTXFYb1Nsajc2SG9iNlVn
            T09CbXovbkJDVVZHeGpqOFcwSUpoOEUKo59Wq6wDcQb+LGhJ19cr7mCm6tR3sHyO
            Z9qQU44jmqvyPFEhzy9P7Ir7UZgilCHqLF7W8ld9+vp51jRJULCahw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T13:08:54Z"
    mac: ENC[AES256_GCM,data:Kcah4w6amcnCJJXmnxaAdpypVQiavl4z6m5B+qHbbkR56z8tWPRvXuYGh09vkMOhunhJmqUNikt6gHr/Gxb52gFGh7uYiJZHL5RdU4N7bCmwH06F9VJGJolHmOdvH2ondZFG1WUGVOykbGreTaSOTyF0bxhQMev0vtNnb7cLBZw=,iv:xdg8tmVH/JPKYiQV+30P9CexxcGUOUqbrOgEJmZstZs=,tag:Tm9+4D28WPSQcm/TaZD9ig==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
