apiVersion: v1
kind: Secret
metadata:
    name: listmonk-postgres
    namespace: listmonk
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Hq1/WHuTgt56wD3jzpU5voW5DKUFXGtQFI1aRRRzRDvtGxsn1mI2M7O01EriYiOG8q7AsIfedgEoqZXpMTHLRBs=,iv:qW+mz73sEbAmF4myEqXWCvLdqvzx070F/sNcuobAKDI=,tag:LQAsZpwk6yOk6euQGwd2yA==,type:str]
sops:
    age:
        - recipient: age1uu9uughvqte75n94w6equ5ak40tw646k9487y32eh32ygnx3c9kseznu9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdHlVNHpwaURwQmtwc0pw
            L3BlSktCSElmMlQ4UDV1eGMyYnNPZS9idmlVCkxwcUZGZlRGdmtnTFNDOWtVWSt6
            TDBtWGdyelNxTVhoY04vb1pZKzlXL2cKLS0tIHpWNm0wbElLV2NDM2dLTlV3ZXg0
            clpzNXJLREdKOHd5RTFnRFdxMEZQNUEKhDAKdW8cIeHzVIMH1CSJnNkhdhxO6bO4
            lBsX++BoDd1tDSoMFXR6EpNd+JVDp6IpxEnrui6/406+x1lPpF4/xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T12:59:12Z"
    mac: ENC[AES256_GCM,data:e6nb1MxVEZezBx9N5xMJ/NzRTdkgXhNGEej6cguQxa7mn5ZYnSZasY9udX3Xr65FL8l2tzIex83XBD+RC8ge8awqJYL/Wrp5ONa/HuwADsCgClHLKst/U1Dmbw63rM0XeGTiyWrXXVQiEBPuSfiWZ6GoOzRtmC80RrCD3mbp35M=,iv:5Q8/88jrwDf/r7CFIA5/7T9TqpF4tsIAJ+cwKOc6HRA=,tag:dB7iYV3UVlBEIQicAKyeRQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
